name: build test
on:
  workflow_call:
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    name: build test
    steps:
      - name: checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: 'latest'
      - name: install dependencies
        run: bun i
      - name: set pages domain
        run: |
          sed -i 's!text.0w.nz!xero.github.io/text0wnz!' .env
      - name: build application
        run: |
          bun bake
          printf "\n%s\n%s\n" "https://github.com/xero/text0wnz" "https://teXt.0w.nz" >> LICENSE.txt
          cp LICENSE.txt dist/
      - name: check build artifacts
        run: |
          # dirs
          test -d dist/ui
          test -d dist/ui/js
          test -d dist/ui/img
          test -d dist/ui/fonts
          # static files
          test -f dist/ui/img/android-launchericon-48-48.png
          test -f dist/ui/img/apple-touch-icon.png
          test -f dist/ui/img/favicon-96x96.png
          test -f dist/ui/img/favicon.ico
          test -f dist/ui/img/favicon.svg
          test -f dist/ui/img/logo.png
          test -f dist/ui/img/web-app-manifest-192x192.png
          test -f dist/ui/img/web-app-manifest-512x512.png
          test -f dist/ui/topazplus_1200.woff2
          test -f dist/favicon.ico
          test -f dist/humans.txt
          test -f dist/index.html
          test -f dist/robots.txt
          test -f dist/service.js
          test -f dist/sitemap.xml
          test -f dist/site.webmanifest
          # hashed files
          [ -n "$(compgen -G "dist/ui/img/screenshot*.png")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/canvas*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/core*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/editor*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/fileops*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/network*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/palette*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/tools*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/js/websocket.js")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/icons*.svg")" ] || exit 1
          [ -n "$(compgen -G "dist/ui/stylez*.css")" ] || exit 1
          echo "Build successful"
      - name: upload build results as artifact
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: editor-build
          path: dist
          retention-days: 3
      - name: add artifact download info to summary
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "### :package: build Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- artifacts for this run are available under the **Artifacts** section of [this workflow run]($RUN_URL)." >> $GITHUB_STEP_SUMMARY
          echo "- or use the cli: \`gh run download ${{ github.run_id }} -n editor-build\`" >> $GITHUB_STEP_SUMMARY
