name: build and publish editor docker image
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  push:
    paths:
      - 'Dockerfile'
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      build_tag: ${{ steps.get_sha.outputs.build_tag }}
    steps:
      - name: checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: 'latest'
      - name: version bump
        id: version-bump
        run: |
          git fetch origin main
          git checkout main
          git pull origin main --ff-only
          BUILDTIME=$(date -u +%Y-%m-%d)
          VERSION=$(bun -p "require('./package.json').version")
          BLINE=$(awk '/org.opencontainers.image.created/ { print NR; exit }' Dockerfile)
          VLINE=$(awk '/org.opencontainers.image.version/ { print NR; exit }' Dockerfile)
          sed -i "${BLINE}c\LABEL org.opencontainers.image.created=\"${BUILDTIME}\"" Dockerfile
          sed -i "${VLINE}c\LABEL org.opencontainers.image.version=\"${VERSION}\"" Dockerfile
          echo "buildtime=$BUILDTIME" >> "$GITHUB_OUTPUT"
          echo "buildversion=$VERSION" >> "$GITHUB_OUTPUT"
          git add Dockerfile
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            COMMIT_NAME="${{ github.event.head_commit.author.name }}"
            COMMIT_EMAIL="${{ github.event.head_commit.author.email }}"
            if [ -z "$COMMIT_NAME" ]; then
              COMMIT_NAME="${{ github.actor }}"
              COMMIT_EMAIL="${{ github.actor }}@users.noreply.github.com"
            fi
            if [ -z "${{ github.event.head_commit.message }}" ]; then
              COMMIT_MSG="${{ github.event.head_commit.message }}"
            else
            COMMIT_MSG="$(git log -1 --pretty=%s || true)"
            fi
            if [ -z "$COMMIT_MSG" ]; then
              COMMIT_MSG="chore(container) docker build"
            fi
            git config --global user.name "$COMMIT_NAME"
            git config --global user.email "$COMMIT_EMAIL"
            git commit --author="$COMMIT_NAME <$COMMIT_EMAIL>" -m "$COMMIT_MSG"
            git push
          fi
      - name: set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: login to github container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: login to docker hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: extract metadata
        id: meta
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            xerostyle/text0wnz
          flavor: |
            latest=true
          tags: |
            type=raw,value=latest
            type=sha,format=short,prefix=sha-
      - name: get docker short sha
        id: get_sha
        run: |
          SHA=$(echo "${{ steps.meta.outputs.tags }}" | grep '^sha-' | head -n1)
          echo "build_tag=$SHA" >> $GITHUB_OUTPUT
      - name: build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          annotations: |
            org.opencontainers.image.authors=https://github.com/xero/text0wnz/graphs/contributors
            org.opencontainers.image.description=Retro Text Art Editor for ANSI/ASCII/NFO/XBIN Files Rebooted for the Modern Web
            org.opencontainers.image.documentation=https://github.com/xero/text0wnz/wiki
            org.opencontainers.image.source=https://github.com/xero/text0wnz
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=text0wnz
            org.opencontainers.image.url=https://text.0w.nz
            org.opencontainers.image.created="${{ steps.version-bump.outputs.buildtime }}"
            org.opencontainers.image.version="${{ steps.version-bump.outputs.buildversion }}"
