name: e2e tests
on:
  workflow_call:
    inputs:
      shard:
        required: false
        type: string
        default: '1/1'
permissions:
  contents: read
  packages: read
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xero/text0wnz/ci:latest
      options: --user root
    steps:
      - name: checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: install project dependencies
        run: bun i
      - name: set localhost domain
        run: |
          sed -i 's!text.0w.nz!localhost!' .env
      - name: build application
        run: CI=actions bun bake
      - name: set artifact name
        id: set-artifact-name
        shell: bash
        run: |
          SHARD="${{ inputs.shard || '1/1' }}"
          ARTIFACT_NAME="blob-report-${SHARD//\//-}"
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
      - name: run e2e tests
        run: CI=actions bun test:e2e --shard=${{ inputs.shard }}
        env:
          HOME: /root
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:8060
      - name: upload report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: ${{ steps.set-artifact-name.outputs.artifact_name }}
          path: blob-report
          retention-days: 1
