name: lint
on:
  workflow_call:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint code
    steps:
      - name: checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: "latest"
      - name: install dependencies
        run: bun i
      - name: run linter tests
        run: bun lint:check
