name: merge playwright reports
on:
  workflow_call:
    inputs:
      retention-days:
        required: false
        type: number
        default: 14
permissions:
  contents: read
jobs:
  merge-reports:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: install bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: 'latest'
      - name: install playwright
        run: bunx playwright install
      - name: download blob reports
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: merge report
        run: bunx playwright merge-reports --reporter html ./all-blob-reports
      - name: upload merged report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: merged-playwright-report
          path: playwright-report
          retention-days: ${{ inputs.retention-days }}
